# # complex objects have schema definitions
# definitions:
#   v0@ErrorResponse:
#     required:
#       - error
#     properties:
#       error:
#         type: object
#         properties:
#           message:
#             type: string
#           details:
#             type: array
#             items:
#               type: object
#               properties:
#                 message:
#                   type: string
#                 value:
#                   type: string
