paths:
  /v0/login:
    x-swagger-router-controller: v0/components/users/controller
    get:
      tags:
        - v0 | User
      summary: login
      description: user login
      operationId: login
      parameters:
        - name: username
          in: query
          required: true
          type: string
          description: Username
        - name: password
          in: query
          required: true
          type: string
          description: password
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/v0@Response"
        "204":
          description: No content
        default:
          description: Error
          schema:
            $ref: "#/definitions/v0@ErrorResponse"
  /v0/signup:
    x-swagger-router-controller: v0/components/users/controller
    post:
      tags:
        - v0 | User
      summary: add a new user
      description: create a new user
      operationId: signup
      parameters:
        - name: body
          in: body
          schema:
            type: object
            required:
              - username
              - password
              - name
              - contact
            properties:
              username:
                type: string
                description: Username
              password:
                type: string
                description: password
              name:
                type: string
                description: Name of user
              contact:
                type: string
                description: Contact of user
              gender:
                type: string
                description: Gender of user
                enum: 
                  - Male
                  - Female
                  - Other
              address:
                type: string
                description: Address of user
              country:
                type: string
                description: Country of user
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/v0@Response"
        "204":
          description: No content
        default:
          description: Error
          schema:
            $ref: "#/definitions/v0@ErrorResponse"
  /v0/search_users:
    x-swagger-router-controller: v0/components/users/controller
    get:
      tags:
        - v0 | User
      summary: Search users list
      description: get the users list
      operationId: searchUsers
      parameters:
        - name: authorization
          in: header
          required: true
          type: string
          description: Auth token
        - name: name
          in: query
          type: string
          description: name
        - name: contact
          in: query
          type: string
          description: contact
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/v0@Response"
        "204":
          description: No content
        default:
          description: Error
          schema:
            $ref: "#/definitions/v0@ErrorResponse"
  /v0/logout:
    x-swagger-router-controller: v0/components/users/controller
    delete:
      tags:
        - v0 | User
      summary: Logout
      description: Delete the session
      operationId: logout
      parameters:
        - name: authorization
          in: header
          required: true
          type: string
          description: Auth token
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/v0@Response"
        "204":
          description: No content
        default:
          description: Error
          schema:
            $ref: "#/definitions/v0@ErrorResponse"