swagger: "2.0"
info:
  version: "1.0.0"
  title: Users-App
  description: APIs exposing RESTful Users App endpoints
# Point to base URL
host: localhost:3000

# basePath prefixes all resource paths
basePath: /api
#
schemes:
  - http

# format of bodies a client can send (Content-Type)
consumes:
  - application/json
  - multipart/form-data
# format of the responses to the client (Accepts)
produces:
  - application/json
